name:    yesod-book
version: "0.0.0"

dependencies:
- base
- yesod
- time

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  yesod-book:
    main: Log.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-book
